version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rpjc/hubfront_nextjs:latest
    container_name: hubfront_nextjs  
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://tomodachi.mooo.com
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next:/app/.next
    restart: unless-stopped
    command: npm run dev

volumes:
  node_modules:
    driver: local    # Uses the local driver to store the volume
  next:
    driver: local    # Uses the local driver to store the volume